### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by YarikineZ** [AppLoidx/vk_bot#2]
Подскажи пожалуйста, в чем может быть дело? Твой код не менял.

![image](https://user-images.githubusercontent.com/38810461/59760537-39dece00-929b-11e9-863b-20a79563eba2.png)

**Comment by YarikineZ** [comment]
В общем, код устарел. Переписал функцию, все заработало. 
def write_msg(user_id, message,random_id=1):
    vk.method('messages.send', {
        'user_id': user_id,
        'message': message,
        'random_id': random_id
    })

**Comment by AppLoidx** [comment]
Да, я пофиксил. Вообще лучше использовать какую-нибудь математическую функцию для рандома, например, `random.randint(a,b)`.

Функцию в примере исправил на такой вот код:
```python
def write_msg(user_id, message):
    vk.method('messages.send', {'user_id': user_id, 'message': message, 'random_id': random.randint(0, 2048)})

```

Тем не менее, если токен был зарегистрирован раньше апдейта, то можно и без этого параметра (старый API, скажем так). Поэтому не заметил :)
